### ISSUE TITLE
'near' keyword is ignored in `attrs.Time`

### ISSUE THREAD

**Issue by wtbarnes** [dstansby/sunpy-soar#7]
`attrs.Time` allows for a `near` kwarg such that, within the range specified by `start` and `end`, only the observation nearest that time specified to `near` is returned. When passing a `Time` attr with `near`, `sunpy_soar` ignores this keyword and returns every result in the `start,end` range.

As an example,

```python
import sunpy_soar
from sunpy.net import attrs, Fido
from sunpy_soar import attrs as soar_attrs

q = Fido.search(
    attrs.Time('2021-04-21 18:03:19', end='2021-04-21 21:04:04', near='2021-04-21 19:33:41'),
    attrs.Level(2),
    attrs.Instrument('EUI'),
    soar_attrs.Identifier('EUI-FSI174-IMAGE'),
)
```
returns 48 results, not 1. A similar query to the VSO for AIA 171 data would return a single result close to '2021-04-21 19:33:41'.

This may not be a bug per se as I'm not sure if the SOAR API supports this at all so feel free to close this if that is the case.

**Comment by dstansby** [comment]
Thanks for opening - should be possible to implement this at least on the `sunpy-soar` side by filtering the results we get back.

**Comment by wtbarnes** [comment]
Would a `post_search_hook` be the right approach here?

**Comment by dstansby** [comment]
With https://github.com/dstansby/sunpy-soar/pull/8#issuecomment-955744946 for context, I think this should be implemented as a more general solution upstream in sunpy, so other clients benefit that don't support ``near`` in the server query. As such I'm going to close this as won't fix, but I've added a note about this to the README here: https://github.com/dstansby/sunpy-soar/pull/14
